fail_fast: false
repos:
- repo: local
  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      args: ["--reports=n", "--jobs=0", "--rcfile=.pylintrc"]
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      args: ["--profile=black"]
    - id: toml-sort
      name: toml-sort
      entry: toml-sort
      language: system
      files: pyproject.toml
      args: ["--in-place", "-a", "pyproject.toml"]
